Repository ahanapradhan/UnionExtraction, pull requests merged in 2024-05, with the labels that each got.

#91 union + outer join
  mysite/unmasque/src/core/abstract/AppExtractorBase.py
  mysite/unmasque/src/core/abstract/GenerationPipeLineBase.py
  mysite/unmasque/src/core/db_restorer.py
  mysite/unmasque/src/core/equi_join.py
  mysite/unmasque/src/core/executable.py
  mysite/unmasque/src/core/filter.py
  mysite/unmasque/src/core/from_clause.py
  mysite/unmasque/src/core/nullfree_executable.py
  mysite/unmasque/src/core/outer_join.py
  mysite/unmasque/src/core/projection.py
  mysite/unmasque/src/core/union.py
  mysite/unmasque/src/core/union_from_clause.py
  mysite/unmasque/src/pipeline/OuterJoinPipeLine.py
  mysite/unmasque/src/pipeline/UnionPipeLine.py
  mysite/unmasque/src/pipeline/abstract/TpchSanitizer.py
  mysite/unmasque/src/util/configParser.py
  mysite/unmasque/src/util/utils.py
  mysite/unmasque/test/Algo1Test.py
  mysite/unmasque/test/FilterTest.py
  mysite/unmasque/test/NullFreeExeTest.py
  mysite/unmasque/test/OjAndUnionTest.py
  mysite/unmasque/test/ProjectionTest.py
  mysite/unmasque/test/ViewMinimizerTest.py
  mysite/unmasque/test/WhereClauseTest.py
  mysite/unmasque/test/regression/ExtractionTest.py
  mysite/unmasque/test/regression/OuterJoinExtractionTest.py
  mysite/unmasque/test/regression/UnionPipeLineTest.py
  mysite/unmasque/test/util/TPCH_backup_restore.py
Labels: enhancement

#97 Union+outer join
  mysite/unmasque/src/core/QueryStringGenerator.py
  mysite/unmasque/src/core/abstract/AppExtractorBase.py
  mysite/unmasque/src/core/abstract/ExtractorBase.py
  mysite/unmasque/src/core/abstract/GenerationPipeLineBase.py
  mysite/unmasque/src/core/abstract/MinimizerBase.py
  mysite/unmasque/src/core/db_restorer.py
  mysite/unmasque/src/core/executable.py
  mysite/unmasque/src/core/from_clause.py
  mysite/unmasque/src/core/nep.py
  mysite/unmasque/src/core/nullfree_executable.py
  mysite/unmasque/src/core/outer_join.py
  mysite/unmasque/src/core/view_minimizer.py
  mysite/unmasque/src/pipeline/ExtractionPipeLine.py
  mysite/unmasque/src/pipeline/UnionPipeLine.py
  mysite/unmasque/src/pipeline/abstract/TpchSanitizer.py
  mysite/unmasque/src/util/PostgresConnectionHelper.py
  mysite/unmasque/test/regression/UnionPipeLineTest.py
  mysite/unmasque/test/util/TPCH_backup_restore.py
Labels: enhancement

#101 OJ and NEP integration
  mysite/unmasque/src/core/QueryStringGenerator.py
  mysite/unmasque/src/core/nep.py
  mysite/unmasque/src/core/outer_join.py
  mysite/unmasque/src/pipeline/ExtractionPipeLine.py
  mysite/unmasque/src/pipeline/OuterJoinPipeLine.py
  mysite/unmasque/src/pipeline/abstract/Comparator.py
  mysite/unmasque/src/pipeline/fragments/NepPipeLine.py
  mysite/unmasque/test/regression/ExtractionTest.py
  mysite/unmasque/test/regression/NepExtractionTest.py
  mysite/unmasque/test/regression/UnionPipeLineTest.py
Labels: enhancement

#107 Outer Join interaction with other features
  .idea/UnionExtraction.iml
  README.md
  mysite/config.ini
  mysite/create_indexes.sql
  mysite/unmasque/src/core/abstract/GenerationPipeLineBase.py
  mysite/unmasque/src/core/abstract/MinimizerBase.py
  mysite/unmasque/src/core/aggregation.py
  mysite/unmasque/src/core/dataclass/pgao_context.py
  mysite/unmasque/src/core/executable.py
  mysite/unmasque/src/core/factory/PipeLineFactory.py
  mysite/unmasque/src/core/groupby_clause.py
  mysite/unmasque/src/core/limit.py
  mysite/unmasque/src/core/nep.py
  mysite/unmasque/src/core/nullfree_executable.py
  mysite/unmasque/src/core/orderby_clause.py
  mysite/unmasque/src/core/outer_join.py
  mysite/unmasque/src/core/projection.py
  mysite/unmasque/src/core/view_minimizer.py
  mysite/unmasque/src/main_cmd.py
  mysite/unmasque/src/pipeline/ExtractionPipeLine.py
  mysite/unmasque/src/pipeline/OuterJoinPipeLine.py
  mysite/unmasque/src/pipeline/fragments/DisjunctionPipeLine.py
  mysite/unmasque/src/util/QueryStringGenerator.py
  mysite/unmasque/src/util/configParser.py
  mysite/unmasque/src/util/constants.py
  mysite/unmasque/src/util/utils.py
  mysite/unmasque/test/AggregationTest.py
  mysite/unmasque/test/AoaOracleTest.py
  mysite/unmasque/test/ConfigParserTest.py
  mysite/unmasque/test/GroupByTest.py
  mysite/unmasque/test/OuterJoinProjectionTest.py
  mysite/unmasque/test/ProjectionGroupByAggTest.py
  mysite/unmasque/test/UtilsTest.py
  mysite/unmasque/test/regression/DisjunctionExtractionTest.py
  mysite/unmasque/test/regression/ExtractionTest.py
  mysite/unmasque/test/regression/OuterJoinExtractionTest.py
Labels: bug

#112 Between filter corrected.
  mysite/unmasque/src/core/filter.py
Labels: bug

#110 Extended features bugfix and integration
  .gitignore
  mysite/unmasque/src/core/abstract/GenerationPipeLineBase.py
  mysite/unmasque/src/core/abstract/MutationPipeLineBase.py
  mysite/unmasque/src/core/abstract/un2_where_clause.py
  mysite/unmasque/src/core/aggregation.py
  mysite/unmasque/src/core/db_restorer.py
  mysite/unmasque/src/core/filter.py
  mysite/unmasque/src/core/groupby_clause.py
  mysite/unmasque/src/core/limit.py
  mysite/unmasque/src/core/nep.py
  mysite/unmasque/src/core/orderby_clause.py
  mysite/unmasque/src/core/outer_join.py
  mysite/unmasque/src/core/projection.py
  mysite/unmasque/src/pipeline/OuterJoinPipeLine.py
  mysite/unmasque/src/pipeline/fragments/NepPipeLine.py
  mysite/unmasque/src/util/QueryStringGenerator.py
  mysite/unmasque/test/UtilsTest.py
  mysite/unmasque/test/regression/AllFlagExtractionTest.py
  mysite/unmasque/test/regression/DisjunctionExtractionTest.py
  mysite/unmasque/test/regression/ExtractionTest.py
  mysite/unmasque/test/regression/NepExtractionTest.py
  mysite/unmasque/test/regression/OuterJoinExtractionTest.py
  mysite/unmasque/test/regression/UnionPipeLineTest.py
Labels: bug, enhancement

#116 Algebraic Predicates feature + random testing bugfixes
  mysite/unmasque/src/core/abstract/GenerationPipeLineBase.py
  mysite/unmasque/src/core/abstract/MinimizerBase.py
  mysite/unmasque/src/core/abstract/filter_holder.py
  mysite/unmasque/src/core/aoa.py
  mysite/unmasque/src/core/equi_join.py
  mysite/unmasque/src/core/executable.py
  mysite/unmasque/src/core/filter.py
  mysite/unmasque/src/core/limit.py
  mysite/unmasque/src/core/nep.py
  mysite/unmasque/src/core/nullfree_executable.py
  mysite/unmasque/src/core/orderby_clause.py
  mysite/unmasque/src/core/projection.py
  mysite/unmasque/src/pipeline/ExtractionPipeLine.py
  mysite/unmasque/src/util/QueryStringGenerator.py
  mysite/unmasque/src/util/aoa_utils.py
  mysite/unmasque/src/util/utils.py
  mysite/unmasque/test/regression/AllFlagExtractionTest.py
  mysite/unmasque/test/regression/AoaExtractionTest.py
  mysite/unmasque/test/util/TPCH_backup_restore.py
Labels: bug, enhancement, AOA

#120 Projection error fixed.
  mysite/unmasque/src/core/aggregation.py
  mysite/unmasque/src/core/filter.py
  mysite/unmasque/src/core/projection.py
Labels: bug

#122 filter (-5) removed.
  mysite/unmasque/src/core/filter.py
Labels: bug

#123 In predicate consolidation in Extraction Pipeline
  mysite/unmasque/src/core/abstract/GenerationPipeLineBase.py
  mysite/unmasque/src/core/aggregation.py
  mysite/unmasque/src/core/aoa.py
  mysite/unmasque/src/core/dataclass/genPipeline_context.py
  mysite/unmasque/src/core/dataclass/generation_pipeline_package.py
  mysite/unmasque/src/core/groupby_clause.py
  mysite/unmasque/src/core/limit.py
  mysite/unmasque/src/core/orderby_clause.py
  mysite/unmasque/src/core/outer_join.py
  mysite/unmasque/src/core/projection.py
  mysite/unmasque/src/pipeline/ExtractionPipeLine.py
  mysite/unmasque/src/pipeline/OuterJoinPipeLine.py
  mysite/unmasque/src/pipeline/fragments/DisjunctionPipeLine.py
  mysite/unmasque/src/util/QueryStringGenerator.py
  mysite/unmasque/test/AggregationTest.py
  mysite/unmasque/test/AoaTestFullPipeline.py
  mysite/unmasque/test/NEPTest.py
  mysite/unmasque/test/ProjectionTest.py
  mysite/unmasque/test/precisionTest.py
  mysite/unmasque/test/regression/AllFlagExtractionTest.py
Labels: enhancement

#128 Truncate return type fixed, get_LB kept in projection.
  mysite/unmasque/src/core/projection.py
  mysite/unmasque/src/util/aoa_utils.py
  mysite/unmasque/src/util/utils.py
Labels: bug

#133 Algebraic Predicates + IN operator
  mysite/unmasque/src/core/abstract/GenerationPipeLineBase.py
  mysite/unmasque/src/core/abstract/filter_holder.py
  mysite/unmasque/src/core/aggregation.py
  mysite/unmasque/src/core/aoa.py
  mysite/unmasque/src/core/dataclass/genPipeline_context.py
  mysite/unmasque/src/core/dataclass/generation_pipeline_package.py
  mysite/unmasque/src/core/filter.py
  mysite/unmasque/src/core/groupby_clause.py
  mysite/unmasque/src/core/limit.py
  mysite/unmasque/src/core/nep.py
  mysite/unmasque/src/core/orderby_clause.py
  mysite/unmasque/src/core/outer_join.py
  mysite/unmasque/src/core/projection.py
  mysite/unmasque/src/pipeline/ExtractionPipeLine.py
  mysite/unmasque/src/pipeline/OuterJoinPipeLine.py
  mysite/unmasque/src/pipeline/abstract/generic_pipeline.py
  mysite/unmasque/src/pipeline/fragments/DisjunctionPipeLine.py
  mysite/unmasque/src/pipeline/fragments/NepPipeLine.py
  mysite/unmasque/src/util/PostgresConnectionHelper.py
  mysite/unmasque/src/util/QueryStringGenerator.py
  mysite/unmasque/src/util/aoa_utils.py
  mysite/unmasque/src/util/utils.py
  mysite/unmasque/test/AggregationTest.py
  mysite/unmasque/test/AoaTestFullPipeline.py
  mysite/unmasque/test/MutationPipelineTest.py
  mysite/unmasque/test/NEPTest.py
  mysite/unmasque/test/ProjectionTest.py
  mysite/unmasque/test/precisionTest.py
  mysite/unmasque/test/regression/AllFlagExtractionTest.py
  mysite/unmasque/test/regression/AoaExtractionTest.py
  mysite/unmasque/test/regression/UN1_tests.py
  mysite/unmasque/test/util/queries.py
Labels: bug, enhancement, AOA
